# Configuration du site
title: "DST Consulting"
name: "DST Consulting"
description: "Solutions de conseil professionnel"
url: "https://dst-consulting.github.io"
baseurl: ""

# Configuration du thème
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Informations de l'auteur
author:
  name: "DST Consulting"
  bio: "Votre partenaire conseil"
  location: "Votre ville, Pays"
  email: "contact@dst-consulting.fr"
  linkedin: "votre-linkedin"

# Navigation
include:
  - _pages

# Configuration des pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Markdown
markdown: kramdown
highlighter: rouge
